project_id = "acfnikpwzavprxkyqqqk"

[functions.predict]
verify_jwt = true

[functions.analyze_bill]
verify_jwt = true

[functions.eco_forecast]
verify_jwt = true

[functions.global_impact]
verify_jwt = false

[functions.design_advisor]
verify_jwt = true

[functions.eco_copilot]
verify_jwt = false
